version: "3"
services:
  hmpps-resettlement-passport-prototype-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-resettlement-passport-prototype-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      #http://hmpps-auth:8080/auth
      - API_BASE_URL_PRISON=https://prison-register-dev.hmpps.service.justice.gov.uk
      #http://prison-api-resettlement-passport-prototype-api:8080
      - API_BASE_URL_OFFENDER_SEARCH=http://prisoner-search:8080


  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth-resettlement-passport-prototype-api
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev,nomis
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api-resettlement-passport-prototype-api:8080

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    container_name: nomis-user-roles-api-resettlement-passport-prototype-api
    depends_on:
      - hmpps-auth
    ports:
      - "8084:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth

  prisoner-search:
    image: wiremock/wiremock:2.35.0
    networks:
      - hmpps
    container_name: prisoner-search-api-resettlement-passport-prototype-api
    depends_on:
      - hmpps-auth
    ports:
      - "8083:8080"
    volumes:
      - ./prisoner-search-data:/home/wiremock

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    container_name: prison-api-resettlement-passport-prototype-api
    depends_on:
      - hmpps-auth
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  localstack:
    image: localstack/localstack:0.14.0
    networks:
      - hmpps
    container_name: localstack-resettlement-passport-prototype-api
    ports:
      - "4566-4597:4566-4597"
      - "8999:8080"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


networks:
  hmpps: